version: "3.2"

services:

  db:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_DATABASE: "Akademik"
      MARIADB_USER: "habibi"
      MARIADB_PASSWORD: "habi123"
      MARIADB_ROOT_PASSWORD: "rootpass"
      MARIADB_TZ: "Asia/Makassar"
    command: "--default-time-zone=+08:00"
    ports:
      - "3306:3306"
    volumes:
      - ./_tmpdb/mariadb:/var/lib/mysql
    networks:
      - uts-pbo

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db:mysql
    environment:
      PMA_HOST: db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootpass
      PMA_ARBITRARY: 1
    volumes:
      - ./_tmpdb/phpmyadmin
    networks:
      - uts-pbo
  
networks:
  uts-pbo:
    external: true
    name: uts-pbo